### ISSUE TITLE
Plot method

### ISSUE THREAD

**Issue by jemus42** [PlantedML/randomPlantedForest#39]
I assume we'd need to tidy up the output from `$fit$get_model()` in some way to be able to visualize it informatively.  
Also depending on the status of `purify` (need more info on that when the time comes).

So far I shortly played around with the output to see what I can make of it, and while I at least recognize values I can't "think them" into a tree structure yet.
We might also be in for some fiddly bits regarding factor variables and associated levels, but we should have all the relevant information stored in `$blueprint$ptypes$predictors` for the original order and `$factor_levels`, which.. also contains the original levels? Okay we might have to check again how we do that.

``` r
library(randomPlantedForest)
train <-  tibble::tibble(
  x1 = rnorm(100, 30, 2),
  x2 = rnorm(100, -50, 2),
  x3 = factor(rbinom(100, 2, 1/2), labels = LETTERS[1:3]),
  y = 1.5 * x1 + -3 * x2 + 2 * as.numeric(x3) + rnorm(100)
)

set.seed(23)
rpfit <- rpf(y ~ ., data = train, max_interaction = 1, ntrees = 2, splits = 5)
mod <- rpfit$fit$get_model()

tree1 <- mod[[1]]
tree1$variables[[2]]
#> [1] 1
tree1$values[[2]]
#> [[1]]
#> [1] -8.203462
#> 
#> [[2]]
#> [1] 2.854149
#> 
#> [[3]]
#> [1] -0.6127117
tree1$intervals[[2]]
#> [[1]]
#>          [,1]      [,2] [,3]
#> [1,] 24.25602 -54.52766    1
#> [2,] 27.85953 -46.34593    3
#> 
#> [[2]]
#>          [,1]      [,2] [,3]
#> [1,] 31.66638 -54.52766    1
#> [2,] 36.46406 -46.34593    3
#> 
#> [[3]]
#>          [,1]      [,2] [,3]
#> [1,] 27.85953 -54.52766    1
#> [2,] 31.66638 -46.34593    3
```

<sup>Created on 2022-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jemus42** [comment]
Note: The more interesting plot method would be for the prediction components, the tree family visualization/printing would be neat though to explain the difference between RPF and vanilla RF.

**Comment by MHiabu** [comment]
Yes, I think the main thing we should focus on is plotting the predicted components:
(a) Plot numeric one-dimensional components as simple scatterplot.
(b) Plot numeric two-dimensional components as heatmaps. 
(c) Components of (multiple) factors  and a numeric variable can be plotted with multiple lines, each corresponding to different factor value (combinations) or as heatmap.
(d) Components of (multiple) factors  and two numeric variables can be visualized  by having multiple heat maps corresponding to different factor value (combinations).
(e) One dimensional factor components can be plotted as bar plots. Two dimensional factors can be plotted as multiple barplots or a heatmap etc.
-----
Of course, one can also think of being able to visualize a tree-family. But this would be a family of trees, i.e., multiple trees.
And this will also probably only work for some purified versions where the multi-variate components are represented as trees. That is, leaves are not overlapping. But I am not sure how to best read that information effectively to have a tree representation....

**Comment by jemus42** [comment]
Yeah I initially thought of the tree-diagram used in the paper to explain the planted-principle. It would be pretty cool to have a ready-made solution for that, but more from an academic perspective I guess.

Regarding the predicted components I haven't figure out how the predictions even work, I might need an explainer on that ore maybe something is not ready on the C-level (or R-level `predict`-method), all I'm getting is `The input X has the wrong dimension`:

``` r
library(randomPlantedForest)
train <-  mtcars[1:20, ]
test <-  mtcars[21:32, ]

ntrees <- 35
set.seed(23)
rpfit <- rpf(mpg ~., data = train, max_interaction = 3, ntrees = ntrees)
pred0 <- predict(rpfit, test)

# Default behavior, "normal" prediction
predict(rpfit, test, components = 0)
#> # A tibble: 12 × 1
#>    .pred
#>    <dbl>
#>  1  24.1
#>  2  18.9
#>  3  21.2
#>  4  18.4
#>  5  18.8
#>  6  30.2
#>  7  29.0
#>  8  20.9
#>  9  22.7
#> 10  21.0
#> 11  19.6
#> 12  26.1

# Anything else: ??
predict(rpfit, test, components = 1)
#> Error in object$fit$predict_matrix(new_data, components): The input X has the wrong dimension in order to calculate f_i(x)
predict(rpfit, test, components = c(0, 1))
#> Error in object$fit$predict_matrix(new_data, components): The input X has the wrong dimension in order to calculate f_i(x)
```

<sup>Created on 2022-11-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jemus42** [comment]
Okay, now that I have a rough understanding on how the component predictions work I think it's clear that we need a different interface from the R side, because `predict` is not suited for the case where the input predictor matrix does not include all original predictors the model was fit on, and it does not support arbitrary output dimensions - the output must always be a matrix with one column per outcome level, or one column in the regression case.

Maybe something like `components(new_data, c)` where `c` would be the `components` vector passed to `predict_matrix` in C++. `c` would need a better name, or the function should have a different name, but in any case we need to move this out of the current `predict` function.

**Comment by jemus42** [comment]
Okay, I have a rough idea how to approach this. Consider this simple regression setup:

``` r
library(randomPlantedForest)

# Regression task, only numeric predictors
train <-  mtcars[1:20, ]
test <-  mtcars[21:32, ]

dim(test)
#> [1] 12 11

set.seed(23)
object <- rpf(mpg ~ ., data = train, max_interaction = 3, ntrees = 35)
```

Here, `test` is a subset of the original data but still contains the outcome `mpg`.
I want to make the following assumptions for what new data for prediction could look like:

1. The outcome may still be included, so we need to remove it before passing it to `predict_matrix`.
2. The predictors must have the same names, but may have a different column order for whatever reason. I don't think it's feasible to try to enforce anything else.
3. If the original data contained `factor` variables, we need to process them the same we do in `predict.rpf`, meaning a call to `preprocess_predictors_predict`. This converts `factor`s to integer variables with the same level order as saved in the `object` during fitting.

## Approach 1

First thing I tried basically:

``` r
extract_components <- function(object, new_data, components = 0) {

  # Enforces column order, type, column names, etc
  # Disabled because it expects every predictor from original fit to be present
  # processed <- hardhat::forge(new_data, object$blueprint)

  # Ensure new data is subset of original predictors, rather than being exactly equal
  orig_predictor_names <- names(object$blueprint$ptypes$predictors)

  # Exclude outcome if still contained in new_data
  new_data <- new_data[, setdiff(names(new_data), names(object$blueprint$ptypes$outcomes))]
  checkmate::assert_subset(names(new_data), orig_predictor_names)

  # Encode factors to (re-)ordered integers according to information saved during model fit
  predictors <- randomPlantedForest:::preprocess_predictors_predict(object, new_data)

  object$fit$predict_matrix(predictors, components)
}
```

Couple of problems:
If new data still contains the outcome, we have to account for that when specifying components and can't just use
`ncol(test)` in this example. Outcome will be removed in extract_components, though

```r
extract_components(object, test, components = 1:(ncol(test) - 1))
#>       [,1]
#>  [1,]    0
#>  [2,]    0
#>  [3,]    0
#>  [4,]    0
#>  [5,]    0
#>  [6,]    0
#>  [7,]    0
#>  [8,]    0
#>  [9,]    0
#> [10,]    0
#> [11,]    0
#> [12,]    0
```

I assume the values specified in components must correspond to the indices of the predictors, right?

Matching indices:

```r
extract_components(object, test[, c(3, 4)], components = 3:4) 
#>               [,1]
#>  [1,] -0.009284119
#>  [2,]  0.047411255
#>  [3,]  0.047411255
#>  [4,]  0.047411255
#>  [5,]  0.047411255
#>  [6,]  0.035113500
#>  [7,] -0.009284119
#>  [8,] -0.009284119
#>  [9,]  0.047411255
#> [10,]  0.012530303
#> [11,]  0.047411255
#> [12,] -0.009284119
```

Non-matching indices give different result:

```r
extract_components(object, test[, c(3, 4)], components = 1:2)
#>             [,1]
#>  [1,] 0.01962303
#>  [2,] 0.01962303
#>  [3,] 0.01962303
#>  [4,] 0.07695637
#>  [5,] 0.07695637
#>  [6,] 0.01962303
#>  [7,] 0.01962303
#>  [8,] 0.01962303
#>  [9,] 0.07695637
#> [10,] 0.07695637
#> [11,] 0.03055756
#> [12,] 0.01962303
```

This means we have to ensure predictor order is identical to the data `rpf()` was fit on.
`hardhat::forge()` does that for us in `predict.rpf()` but since it also expects all predictors present we have to do
that manually or find a different interface.

And if predictor column indices and `components` indices must correspond, we need an interface that "just does that", without having to manually ensure both match up.

## Second Approach

Idea is to pass the column names (or alternatively indices?) of the predictors we want to extract the components for.
This has the benefit of keeping `hardhat::forge` so we get the additional checks for free and the user doesn't have to subset their data for selected columns before passing it to the function.

```r
extract_components_by_name <- function(object, new_data, predictors = NULL) {

  # Ensure selected predictors are subset of original predictors
  checkmate::assert_subset(predictors, choices = names(object$blueprint$ptypes$predictors), empty.ok = FALSE)

  # Enforces column order, type, column names, etc
  processed <- hardhat::forge(new_data, object$blueprint)

  # Encode factors to (re-)ordered integers according to information saved during model fit
  new_data <- randomPlantedForest:::preprocess_predictors_predict(object, processed$predictors)

  # Indices of selected predictors
  components <- match(predictors, colnames(new_data))

  # subset new_data to contain only selected components
  new_data <- new_data[, components, drop = FALSE]

  object$fit$predict_matrix(new_data, components)
}
```

One component, first predictor column in `test` data

```r
extract_components_by_name(object, test, predictors = c("cyl"))
#>           [,1]
#>  [1,] 5.489524
#>  [2,] 4.257956
#>  [3,] 4.257956
#>  [4,] 4.257956
#>  [5,] 4.257956
#>  [6,] 5.489524
#>  [7,] 5.489524
#>  [8,] 5.489524
#>  [9,] 4.257956
#> [10,] 3.411670
#> [11,] 4.257956
#> [12,] 5.489524
```

Two components, 1st and 3rd predictor columns in `test` data

```r
extract_components_by_name(object, test, predictors = c("cyl", "hp"))
#>              [,1]
#>  [1,] -0.04597776
#>  [2,]  0.16394434
#>  [3,]  0.16394434
#>  [4,] -0.22831633
#>  [5,]  0.16394434
#>  [6,] -0.04597776
#>  [7,] -0.04597776
#>  [8,] -0.04597776
#>  [9,] -0.22831633
#> [10,]  0.16408720
#> [11,] -0.22831633
#> [12,] -0.04597776
```

Error cases:
1. trying to pass all columns in test data errors since outcome "mpg" is included
2. If `predictors` not specified, error because there's no reasonable default behavior here (-> point user to predict())

```r
extract_components_by_name(object, test, predictors = names(test))
#> Error in extract_components_by_name(object, test, predictors = names(test)): Assertion on 'predictors' failed: Must be a subset of {'cyl','disp','hp','drat','wt','qsec','vs','am','gear','carb'}, but has additional elements {'mpg'}.

extract_components_by_name(object, test)
#> Error in extract_components_by_name(object, test): Assertion on 'predictors' failed: Must be a subset of {'cyl','disp','hp','drat','wt','qsec','vs','am','gear','carb'}, not empty.
```

Now I'm only confused because I thought selecting two components should return a 2-column matrix 🙃
